services:
- docker

dist: xenial
os: linux
language: bash

env:
  global:
    - secure: Tkx6Rti1G6qI2zHImUAIJaHxkW9tw17J5zfA8tc/4XsWNaAiufeYvQGjqN98wEjBOOwQ8xVncbrhfejO93Go/PJinPkzqdw89cBGcmU0bZ9FjQoMvi60lqvz8agVwkw/MhEpi+ZO0kQtA80qgEWlkpv6tw5Jic0OoajjF4Z2A30XN9a79K5Re3G9frM4qBSYu4Y4TeDRstD4EwhUq6VuYqzfUXoqkAu/KKdJtSqxgx7fyCPFdHcuVqODA3clHwh19VtvO2pjodanLqN9+uV8hM2At1a1iouH97UvNyuNAKHaWsFdQwv7DzUAlKLLI/TnYSfH9l8unzK71kydq8v8PMICRRreJc2pIqrVTAmjxDmanUR+K9iCziFdRoIml+5kFRkF2QQpegjmk0NQWCB856T+Cs6M63G0Dmg/kPEfslOHVrnuApEijfmMUKCGesh+9oE9kYH2/hTThOLAXDerbn8ZnbyIKs1iwap05t5EyuFd52P9QndtG+Ti8TNvars9612HKKOV81Ff6wJiKI5uJLr243MAMNMLnU09VziAyjwOPqwDllskj6HvZBzBxuKf1Ky9aUL+/oTGPGfDc6udycxFSW1YQOf7EvAYyohn3WCewDxg5ERaNipmc60jjz+Tzbs65KLVFk1JxpOmt716ghF9hwCfKEdH2scv4iNfvj4=
    - secure: L4ZmhoV68FcbE08OKnHwi0SRgbByh+PA5NuhKOyPZ+QNBaN+vUx4ZGMvU1vxujSu495vHlyJkOwTp25o/U5EcvgNW3FsG+aY2HgWywgcPwxbpRBJcfAkPDOx+iIizfcTzzyY7jrxKQIdiXPu2RTpcSmfMAULhxFdqfrV/Uf5XXZ3UyNq5itB65yhvhZ81ABprzWQ3hlSJZ32puwediF308t8BuTf3zqkTUKQd44NMxrBf9V9DsxbevzgRryrSP1/C4a0KuWcpMSVbBHzFwCYILJGNgEBhgCPVff5KLYe8wPZFmc4MnQYkvfOlSta1hbF2UyzeBkDU+UzpiIe2FOFWwPu9ngAiul4w0Vx+AkZZ7IcqCRNRj/6JAEYpm6nabhKdDaIPcxZyQpLXYS39+2BJySJnzwq1AdqH3d8UxC+A19YGrHxsQJgB/SgbOXGbACBF9VKcwR3jNEWP0jKxFQ4tM7S8h+ho0Qb80a5caYSCpnmYe/EkE5Nempq1UF2yMmZSYlb6eZhtHGk6q+hkYezRebcI6BPepsUrN72T8KWw9YjQa9QQCUl742qaqg0915qbqV4MyzI4THonfkqk9H9c5XtTgugsUXYJtzM6RzBy7N1AfJo7exR88nL2sK4+10YuAWMWNZvDPreCwqg/L0KFEI8zYREVgafKvqUjiBbnZ4=

script:
- "./setup.sh prod"
- docker-compose build

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]];
  then echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin;
  docker-compose push;
  fi

notifications:
  email: false
