services:
- docker

dist: xenial
os: linux
language: bash

script:
- "./setup.sh prod"
- docker-compose build
- "./test/testApp.sh prod"

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]];
  then echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin;
  docker-compose push;
  fi

notifications:
  email: false
