services:
  - docker

dist: xenial
os: linux
language: bash

script:
  - ./setup.sh prod
  - docker-compose build

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    docker-compose push;
    fi

# don't notify me when things fail
notifications:
  email: false
