version: "3"

services:
  fe:
    build:
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:4000
    volumes:
      - ./:/opt/app
      - node_modules:/opt/app/node_modules

volumes:
  node_modules:
