version: "3"

services:
  fe:
    build:
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - PORT=3000
      - DEV_PORT=3001
    volumes:
      - ./:/opt/app
      - node_modules_fe:/opt/app/node_modules
  e2e:
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json
      - node_modules_e2e:/app/node_modules

volumes:
  node_modules_fe:
  node_modules_e2e:
