FROM node:11-alpine

RUN apk add --no-cache \
    python make

WORKDIR /opt/app/

COPY package.json yarn.lock ./

# install dev dependencies
RUN yarn --check-files --frozen-lockfile && \
    chmod -R 777 node_modules

# copy files
COPY . ./

# build the bundle and clean up
RUN yarn build && \
    yarn install --production --ignore-scripts --prefer-offline && \
    yarn cache clean

CMD yarn serve
